### ISSUE TITLE
[new feature] Add declared http server.HandlerOptions

### ISSUE THREAD

**Issue by fwhezfwhez** [micro/go-api#18]
Hello, I add some declared http handler options and have pulled a request.
I've tested it locally and everything is ok.

** What's benifits?**
We used to do like this:
```go
	 user.RegisterUserHandler(userService.Server(), new(User), api.WithEndpoint(&api.Endpoint{
		  Name: "User.GetToken",
		  Path: []string{"/user/token/"},
		  Method: []string{"POST"},
		  Handler: rpc.Handler,
	 }),api.WithEndpoint(&api.Endpoint{
		  Name: "User.GetUserName",
		  Path: []string{"/user/username/"},
		  Method: []string{"GET"},
		  Handler: rpc.Handler,
	 }))
```
Now we can do it like:
```go
    r := api.NewHttpRouters()
    r.POST("/user/token/", "User.GetToken")
    r.GET("/user/username/", "User.GetUserName")
    // add the officials
    // r = append(r, api.WithEndpoint(&api.Endpoint{	
    //}))

    user.RegisterUserHandler(userService.Server(), new(User), r...)
```
or like this:
```go
	user.RegisterUserHandler(userService.Server(), new(User),
		api.POST("/user/token/", "User.GetToken"),
		api.GET("user/username/", "User.GetUserName"),
	)
```
3q~

**Comment by vtolstov** [comment]
nice thing

**Comment by vtolstov** [comment]
@asim can you merge this?

**Comment by asim** [comment]
No because go-api's interfaces currently need to evolve and this is a very specific change that's going to cause issues in the near future when I break it.

**Comment by vtolstov** [comment]
ok, what you suggest for me, if i need something like this?
(for http path and method bind micro service + micro method, with optional ability to marshal/unmarshal request to micro method request/response)

**Comment by asim** [comment]
What is the static mapping for? Do you want to statically map all API entry points? Just one? Is the expectation to do this in your backend service or as part of an API?

I think there needs to be some separation between go micro and go api. See the router package. We have registry in there but will also have static to allow static mapping.

**Comment by vtolstov** [comment]
I think that best of all allow to map one by one.
So i can write some micro service that acts as like api proxy between my own api and some external, and this service registers inside go-api service.
Also via providing selector to this registration and registry i can have dynamically registered api services.

**Comment by vtolstov** [comment]
router package looks something that i need , but i don't understand how to get something that i need =)

**Comment by asim** [comment]
Go API is pieces of code ripped out of the micro API codebase. It's not yet intended to be used as a library by anyone. There's going to be a lot of refactoring before it becomes useful. I'd advise either to help with that refactoring or find an alternative way to statically map endpoints.

The goal of go API is to provide a go micro like framework for consolidating API entry points. This started as something for http but I believe it will evolve beyond that to be a gateway for many types of protocols. So it requires some refactoring to make that possible. One example is the ability to define mqtt as the gateway protocol but then translate that to anything internally

**Comment by fwhezfwhez** [comment]
@vtolstov 
I looked through and found micro gateway stops those requests whose method is not POST and GET, I guess this restriction has its reason. Before asim eliminates this restriction, r.PATCH,r.PUT,r.DELETE ... are meaningless.
Also I designed a httpResponseWrap to help operate the response writer's http status and its body when some errors occur.emmm,also means few if other restful methods are refused.
Sorry that my pr helps nothing!

**Comment by asim** [comment]
The problem is that the go-api library needs to be refactored before additional changes are made otherwise it makes things a lot more difficult. The API only accepted post requests initially because data needs to be sent as part of the body. Http methods also can't be detected by the RPC application unless using a specific handler. 

I'm not trying to block the evolution or progress of the tooling. The design needs to be considered before doing anything.

**Comment by vtolstov** [comment]
@asim main problem that for many things it needs to be proper designed and refactored, but people need to solve it own problems now. So now for example i need to create own gateway that suits my needs. But when go-api ready i need to decide use it (and patch needed things) or use own stuff. This is not helps micro to grown.
This is my 2 cents... and sorry for noise.

**Comment by vtolstov** [comment]
@fwhezfwhez what do you think about some micro service that acts as api gateway and have method that receives 
struct {
service_name 
service_method
service_request
service_response
handler? (like http, graphql)
}

and allows to plug this struct to http path with placeholders and http method?
So i want something like you but more flexible. And allows dynamic configuration via rpc like register/deregister...

**Comment by asim** [comment]
Assume the library go-api didn't exist. Then what would you do? It's not here for your use right now. It's here for me to find the right abstractions to compose a better micro API. I don't have a client side solution yet and the proposed solutions are merely going to end up having to change and cause significant disruption. 

If you want a quick solution look at what how this currently works and define something. Otherwise help me fix it.

The micro API uses discovery metadata to determine the handler. You can see the various handlers.  You can see how the router works to match endpoints. All you have to do is set that metadata in your service.

**Comment by vtolstov** [comment]
i can't help because you don't have any roadmap and todo ideally fir issue list to able somebody to help.
If go-api not exists, i write own, but as i say - this is not helps micro ecosystem, because people write own stuff and not improve you stuff.
I think that you need to create roadmap for each repo and some issues , may be with proper tagging like easy, medium, hard and so. so each of micro user can help solv own problems and fix micro stuff.

**Comment by asim** [comment]
Ok fair enough. Feel free to create whatever you need. Please coordinate @fwhezfwhez offline from GitHub issues. Thanks.
